select * from customer 
limit 10;

-- what is the revenue generated by male and female customer?

select gender, sum(purchase_amount) as total_revenue
from customer
group by gender ;

-- Which customer used a discount but still spent more than the avg purchase amount?
select customer_id, purchase_amount
from customer
Where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--which are the top 5 product highest avg review rating.
select item_purchased, round(avg(review_rating ::numeric),2) as avg_product_rating 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare the avg purchase amount between standard and express shopping
select shipping_type,
round(avg(purchase_amount),2)
from customer 
where shipping_type in('Standard','Express') 
group by shipping_type;

--do subscribed cust spend more ? compare avg spend and total revenue between subscriber and non subscribers..
select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--which 5 product have the highest % of purchase with discount applied?
select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--segment customer into  new, returning , loyal based on their total number of previous purchased.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New' 
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer	
)

select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment
order by Number_of_customers desc;

--what are the top 3 product in each category

WITH item_count AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category
                              ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3
ORDER BY category, item_rank;

--are customer who are repeate buyer also likely to subscriber
select subscription_status ,
count(customer_id)as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;

--what is a revenue contribution of each age grp
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
